services:
  database:
    image: postgres:14
    env_file:
      - ./env/db.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend:
    depends_on:
      - database
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./env/backend.env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

volumes:
  postgres_data: