# Generated by Django 5.1.2 on 2024-12-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_feature_image_post_post_search_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='feature_image',
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
